x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.2-python3.12}
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./meltano:/meltano
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres-traffic:
    image: postgres:13
    container_name: db-traffic
    hostname: postgres_traffic
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=traffic
    volumes:
      - ./postgresDB/postgres_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresDB/postgres_init/restore.sh:/docker-entrypoint-initdb.d/restore_schemas.sh
      - ./postgresDB/backup/:/home/
      - ./postgresDB/postgres_init/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ren294_network
    profiles:
      - one
      - etl

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.10
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8084:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    healthcheck:
      start_period: 10s
      interval: 10s
      retries: 20
      test: curl --user superUser:superUser --fail --silent --insecure http://localhost:8081/subjects --output /dev/null || exit 1
    networks:
      - ren294_network
    profiles:
      - one
      - ex1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.10
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2180:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      start_period: 10s
      retries: 20
      interval: 10s
    networks:
      - ren294_network
    profiles:
      - one
      - ex1

  broker:
    image: confluentinc/cp-kafka:7.3.10
    hostname: broker
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    # volumes:
    #   - ./kafka/data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ren294_network
    profiles:
      - one
      - ex1

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.3.10
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "8082:8082"
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: "broker:29092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    networks:
      - ren294_network
    profiles:
      - one
      - ex1

  redpanda:
    image: redpandadata/console:v2.7.1
    container_name: redpanda
    depends_on:
      - broker
    ports:
      - 1010:8080
    environment:
      - KAFKA_BROKERS=broker:29092
    networks:
      - ren294_network
    profiles:
      - redpanda
      - ex1
      - one

  debezium:
    image: debezium/connect:3.0
    restart: always
    container_name: debezium
    hostname: debezium
    depends_on:
      postgres-traffic:
        condition: service_healthy
      broker:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      ENABLE_DEBEZIUM_SCRIPTING: "true"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "-X",
          "GET",
          "http://localhost:8083/connectors",
        ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ren294_network
    profiles:
      - one

  debezium-ui:
    image: debezium/debezium-ui:2.2
    restart: always
    container_name: debezium-ui
    hostname: debezium-ui
    depends_on:
      debezium:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
    networks:
      - ren294_network
    profiles:
      - one

  nifi:
    image: nghia294/nifi:1.27.0
    container_name: nifi
    hostname: nifi
    ports:
      - 8443:8443
    volumes:
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./nifi/data:/home/data
    environment:
      NIFI_WEB_HTTP_PORT: 8443
      NIFI_SECURITY_USER_AUTHORIZER: single-user-authorizer
      NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER: single-user-provider
      NIFI_SECURITY_ALLOW_ANONYMOUS_AUTHENTICATION: true
    networks:
      - ren294_network
    profiles:
      - nifi
      - ex1
      - one

  minio:
    container_name: storage
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ren294
      MINIO_ROOT_PASSWORD: trungnghia294
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - ren294_network
    profiles:
      - minio
      - nifi
      - etl
      - one
      - ex1

  jobmanager:
    image: flink:java8
    container_name: flink-jobmanager
    ports:
      - "8085:8081"
    command: jobmanager
    volumes:
      - ./flink/job/:/opt/flink/usrlib/
      # - ./flink/config/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        s3.endpoint: http://minio:9000
        s3.path.style.access: true
        s3.access-key: ren294
        s3.secret-key: trungnghia294
        fs.s3a.endpoint: http://minio:9000
        fs.s3a.access.key: ren294
        fs.s3a.secret.key: trungnghia294
        fs.s3a.path.style.access: true
        fs.s3a.connection.ssl.enabled: false
    networks:
      - ren294_network
    profiles:
      - flink
      - ex1
      - one

  taskmanager:
    image: flink:java8
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    # volumes:
    #   - ./flink/config/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        s3.endpoint: http://minio:9000
        s3.path.style.access: true
        s3.access-key: ren294
        s3.secret-key: trungnghia294
        fs.s3a.endpoint: http://minio:9000
        fs.s3a.access.key: ren294
        fs.s3a.secret.key: trungnghia294
        fs.s3a.path.style.access: true
        fs.s3a.connection.ssl.enabled: false
    networks:
      - ren294_network
    profiles:
      - flink
      - ex1
      - one

  pinot-zookeeper:
    image: zookeeper:3.9.2
    container_name: pinot-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ren294_network
    profiles:
      - pinot

  pinot-controller:
    image: apachepinot/pinot:1.2.0
    command: "StartController -zkAddress pinot-zookeeper:2181"
    container_name: pinot-controller
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
    depends_on:
      - pinot-zookeeper
    networks:
      - ren294_network
    profiles:
      - pinot

  pinot-broker:
    image: apachepinot/pinot:1.2.0
    command: "StartBroker -zkAddress pinot-zookeeper:2181"
    restart: unless-stopped
    container_name: "pinot-broker"
    ports:
      - "8099:8099"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-broker.log"
    depends_on:
      - pinot-controller
    networks:
      - ren294_network
    profiles:
      - pinot

  pinot-server:
    image: apachepinot/pinot:1.2.0
    command: "StartServer -zkAddress pinot-zookeeper:2181"
    restart: unless-stopped
    container_name: "pinot-server"
    ports:
      - "8098:8098"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx16G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-server.log"
    depends_on:
      - pinot-broker
    networks:
      - ren294_network
    profiles:
      - pinot

  redis:
    container_name: redis_traffic
    image: redis/redis-stack:7.4.0-v0-arm64
    ports:
      - 6379:6379
      - 13333:8001
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - ./redis/data:/data
    networks:
      - ren294_network
    profiles:
      - ex1
      - one

networks:
  ren294_network:
    driver: bridge
