{
 "title": "Clickhouse",
 "time": { "from": "2024-12-22T08:46:53.836Z", "to": "2024-12-22T08:52:01.931Z" },
 "panels": [
  {
   "title": "BlockActiveTime",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram0 +201",
     "legendFormat": "Ram 0"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram1 +432",
     "legendFormat": "Ram 1"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram2 +331",
     "legendFormat": "Ram 2"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram3 +303",
     "legendFormat": "Ram 3"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram4 +211",
     "legendFormat": "Ram 4"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram5 +101",
     "legendFormat": "Ram 5"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram6 +11",
     "legendFormat": "Ram 6"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram7 +241",
     "legendFormat": "Ram 7"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram8 +200",
     "legendFormat": "Ram 8"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram9 +222",
     "legendFormat": "Ram 9"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram10 +302",
     "legendFormat": "Ram 10"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockDiscardBytes_ram11 +355",
     "legendFormat": "Ram 11"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram12",
     "legendFormat": "Ram 12"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram13 +323",
     "legendFormat": "Ram 13"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram14",
     "legendFormat": "Ram 14"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockActiveTime_ram15 +422",
     "legendFormat": "Ram 15"
    }
   ]
  },
  {
   "title": "Repica Queue",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxQueueSize + ClickHouseAsyncMetrics_AsynchronousHeavyMetricsCalculationTimeSpent*0.1",
     "legendFormat": "ReplicaMaxQueueSize"
    },
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasSumInsertsInQueue + ClickHouseAsyncMetrics_AsynchronousHeavyMetricsCalculationTimeSpent*0.2",
     "legendFormat": "ReplicaSumInsertInQueue"
    },
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxInsertsInQueue + ClickHouseAsyncMetrics_AsynchronousHeavyMetricsCalculationTimeSpent*0.3",
     "legendFormat": "ReplicaMaxInsetInQueue"
    },
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxMergesInQueue + ClickHouseAsyncMetrics_AsynchronousHeavyMetricsCalculationTimeSpent*0.35",
     "legendFormat": "ReplicaMaxMergesInQueue"
    }
   ]
  },
  {
   "title": "Calculation Time Spent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_AsynchronousMetricsCalculationTimeSpent",
     "legendFormat": "__auto"
    },
    {
     "expr": "ClickHouseAsyncMetrics_AsynchronousMetricsUpdateInterval",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BlockReadBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_BlockReadBytes_nbd0 + ClickHouseAsyncMetrics_BlockReadBytes_nbd1 +ClickHouseAsyncMetrics_BlockReadBytes_nbd2 + ClickHouseAsyncMetrics_BlockReadBytes_nbd3 + ClickHouseAsyncMetrics_BlockReadBytes_nbd4 + ClickHouseAsyncMetrics_BlockReadBytes_nbd5 + ClickHouseAsyncMetrics_BlockReadBytes_nbd6 + ClickHouseAsyncMetrics_BlockReadBytes_nbd7 + ClickHouseAsyncMetrics_BlockReadBytes_nbd8 + ClickHouseAsyncMetrics_BlockReadBytes_nbd9 + ClickHouseAsyncMetrics_BlockReadBytes_nbd10 + ClickHouseAsyncMetrics_BlockReadBytes_nbd11 + ClickHouseAsyncMetrics_BlockReadBytes_nbd12 + ClickHouseAsyncMetrics_BlockReadBytes_nbd13 + ClickHouseAsyncMetrics_BlockReadBytes_nbd14 + ClickHouseAsyncMetrics_BlockReadBytes_nbd15 +200",
     "legendFormat": "__auto"
    },
    {
     "expr": "ClickHouseAsyncMetrics_BlockReadOps_nbd0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UpdateMetrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_AsynchronousMetricsCalculationTimeSpent ++30",
     "legendFormat": "__auto"
    },
    {
     "expr": "ClickHouseAsyncMetrics_AsynchronousHeavyMetricsUpdateInterval ++2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BytesInMemory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_TotalPrimaryKeyBytesInMemoryAllocated *10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalRowsOfMergeTreeTables",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_TotalRowsOfMergeTreeTables",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}