{
 "title": "Docker",
 "time": { "from": "2024-12-22T10:12:56.620Z", "to": "2024-12-22T10:20:25.563Z" },
 "panels": [
  {
   "title": "Read Bytes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_fs_reads_bytes_total", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Time Started",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_start_time_seconds", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Blkio Usage Total",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_blkio_device_usage_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_writes_bytes_total",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "container_network_receive_packets_total{interface=\"eth0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Swap",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_memory_swap", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "__auto" },
    { "expr": "container_memory_cache", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_cpu_usage_seconds_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_cpu_user_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}