{
 "title": "Flink",
 "time": { "from": "2024-12-22T07:03:51.454Z", "to": "2024-12-22T08:05:53.590Z" },
 "panels": [
  {
   "title": "Record Of Job",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsIn{operator_name=\"Process\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "MemoryUsed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed",
     "legendFormat": "__auto"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Time of Job",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_runningTime",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Count",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_request_total{operator_name=\"Source:_Custom_Source\"}",
     "legendFormat": "{{job_name}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_response_total",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal",
     "legendFormat": "__auto"
    },
    {
     "expr": "flink_jobmanager_taskSlotsAvailable",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}