{
 "title": "Kafka",
 "time": { "from": "2024-12-21T14:38:33.515Z", "to": "2024-12-21T14:43:42.437Z" },
 "panels": [
  {
   "title": "Number of broker and controller",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{instance=\"jmx-exporter-broker:5556\"}",
     "legendFormat": "Broker Count"
    },
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{instance=\"jmx-exporter-controller:5556\"}",
     "legendFormat": "Controller Count"
    }
   ]
  },
  {
   "title": "Server Byte InOut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_bytesrejected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of message",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{instance=\"jmx-exporter-broker:5556\", job=\"kafka\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "FailedRequest",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{instance=\"kafka-exporter:9308\", topic!~\"__consumer_offsets|_schemas|__transaction_state\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Disk read and write",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_linux_disk_read_bytes",
     "legendFormat": "Read Disk"
    },
    {
     "expr": "kafka_server_kafkaserver_linux_disk_write_bytes",
     "legendFormat": "Write Disk"
    }
   ]
  },
  {
   "title": "Netword ResponsedTime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{instance=\"jmx-exporter-controller:5556\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log End and Start Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "kafka_log_log_logendoffset", "legendFormat": "__auto" },
    { "expr": "kafka_log_log_logstartoffset", "legendFormat": "__auto" }
   ]
  }
 ]
}