{
 "title": "Minio",
 "time": { "from": "2024-12-21T15:42:14.149Z", "to": "2024-12-21T16:05:41.086Z" },
 "panels": [
  {
   "title": "Status of nodes",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minio_nodes_offline", "legendFormat": "Nodes Offline" },
    { "expr": "minio_nodes_online", "legendFormat": "Nodes Online" },
    { "expr": "minio_disks_offline", "legendFormat": "Disks Offline" },
    { "expr": "minio_drives_total", "legendFormat": "Drives Total" }
   ]
  },
  {
   "title": "Capacity",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_capacity_usable_free_total",
     "legendFormat": "Capacity Usable Free Total"
    },
    { "expr": "minio_capacity_usable_total", "legendFormat": "Capacity Usable Total" },
    { "expr": "minio_capacity_raw_free_total", "legendFormat": "Capacity Raw Free Total" },
    { "expr": "minio_capacity_raw_total", "legendFormat": "Capacity Free Raw Total" }
   ]
  },
  {
   "title": "Capacity Raw Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "minio_capacity_raw_free_total", "legendFormat": "__auto" },
    { "expr": "minio_capacity_raw_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Capacity Usable Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "minio_capacity_usable_free_total",
     "legendFormat": "__auto"
    },
    { "expr": "minio_capacity_usable_total", "legendFormat": "__auto" }
   ]
  }
 ]
}