{
 "title": "Nifi",
 "time": { "from": "2024-12-21T07:14:09.317Z", "to": "2024-12-21T07:19:28.941Z" },
 "panels": [
  {
   "title": "Amount of flowfile tranferred",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_amount_flowfiles_transferred",
     "legendFormat": "__auto"
    },
    { "expr": "nifi_amount_flowfiles_removed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount of flowfile recieved and sent",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_amount_flowfiles_received{component_type=\"Processor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nifi_amount_flowfiles_sent{component_type=\"OutputPort\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent Used bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 9 },
   "targets": [
    { "expr": "nifi_percent_used_bytes", "legendFormat": "__auto" },
    { "expr": "nifi_percent_used_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Byte sent and received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "targets": [
    { "expr": "nifi_amount_bytes_read", "legendFormat": "__auto" },
    { "expr": "nifi_amount_bytes_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Size content input, output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "targets": [
    { "expr": "nifi_size_content_input_total", "legendFormat": "__auto" },
    { "expr": "nifi_size_content_output_total", "legendFormat": "__auto" },
    { "expr": "nifi_size_content_queued_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Byte read and transferred, written",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 18 },
   "targets": [
    { "expr": "nifi_amount_bytes_read", "legendFormat": "__auto" },
    { "expr": "nifi_amount_bytes_transferred", "legendFormat": "__auto" },
    { "expr": "nifi_amount_bytes_written", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount items input and output",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "nifi_amount_items_input{component_id=\"00d3e338-8366-37ef-c832-94ac30cf9acf\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nifi_amount_items_output{component_id=\"00d3e338-8366-37ef-c832-94ac30cf9acf\"}",
     "legendFormat": "__auto"
    },
    { "expr": "nifi_amount_items_queued", "legendFormat": "__auto" }
   ]
  }
 ]
}