{
 "title": "Redis",
 "time": { "from": "2024-12-21T08:17:31.919Z", "to": "2024-12-21T08:24:19.027Z" },
 "panels": [
  {
   "title": "CPU User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "redis_cpu_user_seconds_total", "legendFormat": "__auto" },
    {
     "expr": "redis_cpu_user_main_thread_seconds_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_cpu_user_children_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis AOF",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_current_rewrite_duration_sec",
     "legendFormat": "Current Rewrite"
    },
    {
     "expr": "redis_aof_last_bgrewrite_status",
     "legendFormat": "Last BgRewrite"
    },
    { "expr": "redis_aof_last_write_status", "legendFormat": "Last Write Status" },
    { "expr": "redis_aof_last_cow_size_bytes", "legendFormat": "Last Cow Size" },
    {
     "expr": "redis_aof_last_rewrite_duration_sec",
     "legendFormat": "Last Rewrite Duration"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_io_threaded_reads_processed",
     "legendFormat": "IO Threaded Reads"
    },
    {
     "expr": "redis_io_threaded_writes_processed",
     "legendFormat": "IO Threaded Writes"
    },
    { "expr": "redis_io_threads_active", "legendFormat": "IO Threaded Active" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_commands_duration_seconds_total",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Number Of Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 9 },
   "targets": [
    { "expr": "redis_db_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "redis_cpu_sys_children_seconds_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_cpu_sys_main_thread_seconds_total",
     "legendFormat": "__auto"
    },
    { "expr": "redis_cpu_sys_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocator Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 15 },
   "targets": [
    { "expr": "redis_allocator_active_bytes", "legendFormat": "__auto" },
    {
     "expr": "redis_allocator_allocated_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "redis_allocator_frag_bytes", "legendFormat": "__auto" },
    { "expr": "redis_allocator_resident_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}