{
 "title": "Spark",
 "time": { "from": "2024-12-22T04:10:49.345Z", "to": "2024-12-22T04:32:04.345Z" },
 "panels": [
  {
   "title": "Minitor Cores",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_application_Distributed_Processing_Demo_1734841878530_cores_Number",
     "legendFormat": "Cores Total"
    },
    {
     "expr": "metrics_application_Distributed_Processing_Demo_1734840715483_cores_Number{job=\"spark-applications\"}",
     "legendFormat": "Core Available"
    }
   ]
  },
  {
   "title": "Pools Metaspace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_jvm_pools_Metaspace_usage_Value",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Minitor Job",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_app_20241222111155_0000_driver_DAGScheduler_job_allJobs_Number",
     "legendFormat": "Total Job"
    },
    {
     "expr": "metrics_app_20241222111155_0000_driver_DAGScheduler_job_activeJobs_Number",
     "legendFormat": "Job Active"
    }
   ]
  },
  {
   "title": "Driver DAG Scheduler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "metrics_app_20241222111155_0000_driver_DAGScheduler_job_allJobs_Value",
     "legendFormat": "__auto"
    },
    {
     "expr": "metrics_app_20241222111155_0000_driver_DAGScheduler_job_activeJobs_Value",
     "legendFormat": "__auto"
    },
    {
     "expr": "metrics_app_20241222111155_0000_driver_CodeGenerator_generatedMethodSize_Count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LiveListener",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_app_20241222111155_0000_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_sql_execution_ui_SQLAppStatusListener_Count",
     "legendFormat": "EventListener"
    },
    {
     "expr": "metrics_app_20241222111155_0000_driver_LiveListenerBus_numEventsPosted_Count",
     "legendFormat": "EventPosted"
    }
   ]
  },
  {
   "title": "Minitor Event",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "metrics_app_20241222111155_0000_driver_LiveListenerBus_numEventsPosted_Count",
     "legendFormat": "__auto"
    },
    {
     "expr": "metrics_app_20241222111155_0000_driver_DAGScheduler_messageProcessingTime_Count",
     "legendFormat": "__auto"
    },
    {
     "expr": "metrics_app_20241222111155_0000_driver_LiveListenerBus_numEventsPosted_Count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HeartBeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "expr": "metrics_app_20241222111155_0000_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Count",
     "legendFormat": "__auto"
    },
    {
     "expr": "metrics_app_20241222111155_0000_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Mean",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "metrics_jvm_heap_usage_Value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Minitor Workers",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "metrics_master_aliveWorkers_Number",
     "legendFormat": "Alive Worker"
    },
    { "expr": "metrics_master_workers_Number", "legendFormat": "Number Worker" },
    { "expr": "metrics_master_apps_Number", "legendFormat": "Number Apps" }
   ]
  }
 ]
}